export const TOVAR_DATA = [
	{
		query: 'easty',
		category: 'other',
		favourite: false,
		basket: false,
		id: 1,
		url: 'https://images.uzum.uz/cd1en3b5a95unf1241n0/original.jpg',
		star: 4.8,
		total_order: 5500,
		title: 'Туалетная бумага Esty 2 слоя, 8 шт',
		total: 257,
		cost: '18 000',
		old_cost: '23 000',
		on_mounth: '2 100',
		about_tovar: [],
		description:
			'Бренд Esty — производитель товаров потребительской бумажной продукции и бумажной продукции для профессионального использования в области гигиены и здоровья из сырья высшего сорта.',
	},
	{
		query: 'samsung_tv',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 2,
		url: 'https://images.uzum.uz/cqkur8ssslomdvnisv3g/original.jpg',
		star: 4.9,
		total_order: 8500,
		title: 'Телевизор Samsung 55", UHD, Smart TV',
		total: 120,
		cost: '3 200 000',
		old_cost: '4 000 000',
		on_mounth: '350 000',
		about_tovar: ['Диагональ: 55"', 'Разрешение: 3840x2160', 'Тип: LED'],
		description:
			'Телевизор Samsung 55" - это UHD-экран с превосходным качеством изображения и функциональностью Smart TV.',
	},
	{
		query: 'iphone_13',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 3,
		url: 'https://images.uzum.uz/cq8fnncqvss6ad8hqkeg/original.jpg',
		star: 4.7,
		total_order: 15000,
		title: 'Смартфон Apple iPhone 13, 128GB',
		total: 75,
		cost: '7 500 000',
		old_cost: '8 200 000',
		on_mounth: '950 000',
		about_tovar: ['Память: 128GB', 'Цвет: черный', 'Процессор: A15 Bionic'],
		description:
			'iPhone 13 - это передовой смартфон от Apple с мощным процессором и отличной камерой.',
	},
	{
		query: 'nike_air_max',
		category: 'fashion',
		favourite: false,
		basket: false,
		id: 4,
		url: 'https://images.uzum.uz/cpnbp036eisq2rkcbcl0/original.jpg',
		star: 4.9,
		total_order: 13000,
		title: 'Кроссовки Nike Air Max 270',
		total: 300,
		cost: '1 200 000',
		old_cost: '1 500 000',
		on_mounth: '140 000',
		about_tovar: ['Размер: 42', 'Цвет: белый', 'Материал: текстиль, резина'],
		description:
			'Nike Air Max 270 - это стильные и удобные кроссовки для активного образа жизни.',
	},
	{
		query: 'dell_inspiron',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 5,
		url: 'https://images.uzum.uz/cqrm3c7frr8a72r7vlvg/original.jpg',
		star: 4.6,
		total_order: 4500,
		title: 'Ноутбук Dell Inspiron 15 3000, 8GB RAM, 256GB SSD',
		total: 50,
		cost: '5 500 000',
		old_cost: '6 000 000',
		on_mounth: '600 000',
		about_tovar: [
			'Оперативная память: 8GB',
			'Хранилище: 256GB SSD',
			'Процессор: Intel Core i5',
		],
		description:
			'Dell Inspiron 15 3000 - это надежный ноутбук для работы и развлечений с мощной начинкой.',
	},
	{
		query: 'loreal_shampoo',
		category: 'beauty',
		favourite: false,
		basket: false,
		id: 6,
		url: 'https://images.uzum.uz/cqh1ihkqvsse8let65cg/original.jpg',
		star: 4.8,
		total_order: 25000,
		title: "Шампунь L'Oreal Paris, 400 мл",
		total: 400,
		cost: '55 000',
		old_cost: '70 000',
		on_mounth: '6 000',
		about_tovar: ['Тип волос: нормальные', 'Эффект: увлажнение'],
		description:
			"L'Oreal Paris шампунь обеспечивает увлажнение и бережный уход за вашими волосами.",
	},
	{
		query: 'samsung_galaxy_s21',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 7,
		url: 'https://images.uzum.uz/cpdegkkcrcfqljg1euhg/original.jpg',
		star: 4.8,
		total_order: 12000,
		title: 'Смартфон Samsung Galaxy S21, 256GB',
		total: 80,
		cost: '6 800 000',
		old_cost: '7 500 000',
		on_mounth: '820 000',
		about_tovar: ['Память: 256GB', 'Цвет: синий', 'Процессор: Exynos 2100'],
		description:
			'Samsung Galaxy S21 — это мощный смартфон с превосходной камерой и производительностью.',
	},
	{
		query: 'dyson_v11',
		category: 'home',
		favourite: false,
		basket: false,
		id: 8,
		url: 'https://images.uzum.uz/cpa4dhfj2e4hhrn32fug/original.jpg',
		star: 4.9,
		total_order: 9000,
		title: 'Беспроводной пылесос Dyson V11',
		total: 45,
		cost: '8 200 000',
		old_cost: '9 500 000',
		on_mounth: '980 000',
		about_tovar: ['Мощность: 185 AW', 'Время работы: до 60 мин', 'Вес: 3 кг'],
		description:
			'Dyson V11 — это мощный и удобный беспроводной пылесос для эффективной уборки дома.',
	},
	{
		query: 'sony_ps5',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 9,
		url: 'https://images.uzum.uz/cq36i0j5qt1gj8de1k00/original.jpg',
		star: 4.9,
		total_order: 22000,
		title: 'Игровая консоль Sony PlayStation 5',
		total: 150,
		cost: '5 000 000',
		old_cost: '5 800 000',
		on_mounth: '600 000',
		about_tovar: [
			'Объем памяти: 825GB',
			'Поддержка 4K',
			'Контроллер: DualSense',
		],
		description:
			'Sony PlayStation 5 — это революционная игровая консоль с поддержкой 4K и уникальными играми.',
	},
	{
		query: 'macbook_pro',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 10,
		url: 'https://images.uzum.uz/cigimfv5d7kom1tj1u00/original.jpg',
		star: 4.8,
		total_order: 7000,
		title: 'Ноутбук Apple MacBook Pro 16", 512GB SSD',
		total: 30,
		cost: '13 000 000',
		old_cost: '14 500 000',
		on_mounth: '1 500 000',
		about_tovar: [
			'Процессор: M1 Pro',
			'Оперативная память: 16GB',
			'Экран: Retina',
		],
		description:
			'Apple MacBook Pro 16" — это мощный ноутбук для профессионалов с передовыми технологиями.',
	},
	{
		query: 'canon_eos_r6',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 11,
		url: 'https://images.uzum.uz/cmt0fmp25ku8jql6diog/original.jpg',
		star: 4.9,
		total_order: 3500,
		title: 'Фотоаппарат Canon EOS R6, 20MP',
		total: 25,
		cost: '10 500 000',
		old_cost: '12 000 000',
		on_mounth: '1 200 000',
		about_tovar: ['Разрешение: 20MP', 'Тип матрицы: CMOS', 'Видеосъемка: 4K'],
		description:
			'Canon EOS R6 — это полнокадровая камера с высоким качеством изображения и поддержкой 4K.',
	},
	{
		query: 'fitbit_charge_5',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 12,
		url: 'https://images.uzum.uz/co9m7v283ve66on3l0ig/original.jpg',
		star: 4.7,
		total_order: 6500,
		title: 'Фитнес-трекер Fitbit Charge 5',
		total: 150,
		cost: '900 000',
		old_cost: '1 200 000',
		on_mounth: '110 000',
		about_tovar: [
			'Мониторинг: пульс, стресс',
			'Время работы: до 7 дней',
			'Совместимость: iOS, Android',
		],
		description:
			'Fitbit Charge 5 — это продвинутый фитнес-трекер для отслеживания здоровья и физической активности.',
	},
	{
		query: 'bose_qc35',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 13,
		url: 'https://images.uzum.uz/cpjbdoe0t1llbtq698n0/original.jpg',
		star: 4.8,
		total_order: 8000,
		title: 'Беспроводные наушники Bose QC35 II',
		total: 200,
		cost: '1 800 000',
		old_cost: '2 200 000',
		on_mounth: '200 000',
		about_tovar: [
			'Шумоподавление',
			'Время работы: 20 часов',
			'Подключение: Bluetooth',
		],
		description:
			'Bose QC35 II — это беспроводные наушники с активным шумоподавлением и превосходным звуком.',
	},
	{
		query: 'dyson_airwrap',
		category: 'beauty',
		favourite: false,
		basket: false,
		id: 14,
		url: 'https://images.uzum.uz/cq34qs0sarnfdo9acph0/original.jpg',
		star: 4.9,
		total_order: 3000,
		title: 'Стайлер для волос Dyson Airwrap',
		total: 40,
		cost: '7 800 000',
		old_cost: '9 000 000',
		on_mounth: '900 000',
		about_tovar: [
			'Мощность: 1300 Вт',
			'Насадки: 6 шт.',
			'Тип: многофункциональный',
		],
		description:
			'Dyson Airwrap — это многофункциональный стайлер для создания разнообразных причесок без перегрева волос.',
	},
	{
		query: 'roomba_i7',
		category: 'home',
		favourite: false,
		basket: false,
		id: 15,
		url: 'https://mionline.uz/image/cachewebp/catalog/o3uhruyuhnm2y2wihmrh3xgt1v08hp7c-600x600.webp',
		star: 4.8,
		total_order: 4000,
		title: 'Робот-пылесос iRobot Roomba i7',
		total: 50,
		cost: '6 500 000',
		old_cost: '7 800 000',
		on_mounth: '780 000',
		about_tovar: [
			'Мощность всасывания: 1700 Па',
			'Время работы: до 90 мин',
			'Площадь уборки: до 180 кв.м.',
		],
		description:
			'Roomba i7 — это интеллектуальный робот-пылесос с высокой мощностью всасывания и точной навигацией.',
	},
	{
		query: 'xiaomi_mi_11',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 18,
		url: 'https://cdn.mediapark.uz/imgs/0abef8df-cc58-49fd-adf3-670cad5bf263_%D0%9C%D0%BE%D0%BD%D1%82%D0%B0%D0%B6%D0%BD%D0%B0%D1%8F-%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C-11300.webp',
		star: 4.8,
		total_order: 12000,
		title: 'Смартфон Xiaomi Mi 11, 256GB',
		total: 65,
		cost: '5 800 000',
		old_cost: '6 700 000',
		on_mounth: '680 000',
		about_tovar: ['Память: 256GB', 'Цвет: белый', 'Процессор: Snapdragon 888'],
		description:
			'Xiaomi Mi 11 — это смартфон с мощной производительностью и потрясающей камерой, идеально подходящий для игр и фотографий.',
	},
	{
		query: 'lenovo_legion_5',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 19,
		url: 'https://minapi.beemarket.uz/prod-media/productImages/thumbnails/medium/1719383517ErEJbThZiiXG.webp',
		star: 4.7,
		total_order: 5000,
		title: 'Ноутбук Lenovo Legion 5, 512GB SSD',
		total: 45,
		cost: '10 200 000',
		old_cost: '11 500 000',
		on_mounth: '1 250 000',
		about_tovar: [
			'Процессор: AMD Ryzen 7',
			'Оперативная память: 16GB',
			'Экран: 15.6" Full HD',
		],
		description:
			'Lenovo Legion 5 — это игровой ноутбук с высоким уровнем производительности и качественным экраном.',
	},
	{
		query: 'philips_airfryer',
		category: 'home',
		favourite: false,
		basket: false,
		id: 20,
		url: 'https://frankfurt.apollo.olxcdn.com/v1/files/vy135s8vs0zl2-UZ/image;s=1000x1000',
		star: 4.8,
		total_order: 8500,
		title: 'Фритюрница Philips Airfryer XXL',
		total: 30,
		cost: '2 500 000',
		old_cost: '3 000 000',
		on_mounth: '300 000',
		about_tovar: ['Объем: 1.4 кг', 'Мощность: 2200 Вт', 'Тип: электрическая'],
		description:
			'Philips Airfryer XXL — это фритюрница для приготовления вкусной и здоровой пищи с минимальным использованием масла.',
	},
	{
		query: 'dyson_supersonic',
		category: 'beauty',
		favourite: false,
		basket: false,
		id: 21,
		url: 'https://tezz.uz/uploads/images/product/543/thumbs/216298-10501050.jpg',
		star: 4.9,
		total_order: 3000,
		title: 'Фен Dyson Supersonic',
		total: 60,
		cost: '4 500 000',
		old_cost: '5 200 000',
		on_mounth: '540 000',
		about_tovar: ['Мощность: 1600 Вт', 'Тип: фен', 'Насадки: 4 шт.'],
		description:
			'Dyson Supersonic — это высокотехнологичный фен для быстрой и бережной сушки волос с различными насадками.',
	},
	{
		query: 'samsung_qled_tv',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 22,
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbbGzAEheOa1Us0JcEURLSZNLqHCWoc3rZcA&s',
		star: 4.9,
		total_order: 7000,
		title: 'Телевизор Samsung QLED 55"',
		total: 20,
		cost: '8 000 000',
		old_cost: '9 500 000',
		on_mounth: '950 000',
		about_tovar: [
			'Диагональ экрана: 55"',
			'Разрешение: 4K UHD',
			'Тип экрана: QLED',
		],
		description:
			'Samsung QLED 55" — это современный телевизор с потрясающим качеством изображения и функциями Smart TV.',
	},
	{
		query: 'dyson_v10',
		category: 'home',
		favourite: false,
		basket: false,
		id: 23,
		url: 'https://cdn.mediapark.uz/imgs/d87f1660-1344-4b18-8ef8-439621985cb5.webp',
		star: 4.9,
		total_order: 7500,
		title: 'Беспроводной пылесос Dyson V10',
		total: 45,
		cost: '7 500 000',
		old_cost: '8 800 000',
		on_mounth: '880 000',
		about_tovar: ['Мощность: 150 AW', 'Время работы: до 60 мин', 'Вес: 2.6 кг'],
		description:
			'Dyson V10 — это легкий и мощный беспроводной пылесос для эффективной уборки в доме.',
	},
	{
		query: 'apple_watch_se',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 24,
		url: 'https://cdn.mediapark.uz/imgs/3889ebc9-01d9-428d-932d-81924504b655.webp',
		star: 4.8,
		total_order: 16000,
		title: 'Смарт-часы Apple Watch SE, 40 мм',
		total: 50,
		cost: '2 500 000',
		old_cost: '3 200 000',
		on_mounth: '320 000',
		about_tovar: [
			'Экран: 40 мм',
			'Мониторинг: пульс, сон',
			'Материал: алюминий',
		],
		description:
			'Apple Watch SE — это стильные и функциональные смарт-часы для повседневного использования.',
	},
	{
		query: 'sony_wh_1000xm4',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 25,
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW583YSFf_TjV8nrl_BWSv0hLHrRLySTlEeg&s',
		star: 4.9,
		total_order: 14000,
		title: 'Беспроводные наушники Sony WH-1000XM4',
		total: 80,
		cost: '2 800 000',
		old_cost: '3 500 000',
		on_mounth: '350 000',
		about_tovar: [
			'Шумоподавление',
			'Время работы: до 30 часов',
			'Подключение: Bluetooth 5.0',
		],
		description:
			'Sony WH-1000XM4 — это премиальные беспроводные наушники с лучшим в классе шумоподавлением и качеством звука.',
	},
	{
		query: 'nintendo_switch_lite',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 26,
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3cWlDVqrC7XYookfi2nd3wyJGHOeT1Vazgw&s',
		star: 4.8,
		total_order: 9000,
		title: 'Игровая консоль Nintendo Switch Lite',
		total: 90,
		cost: '2 500 000',
		old_cost: '3 200 000',
		on_mounth: '320 000',
		about_tovar: [
			'Экран: 5.5"',
			'Встроенная память: 32GB',
			'Автономность: до 7 часов',
		],
		description:
			'Nintendo Switch Lite — это портативная игровая консоль, созданная для игр в дороге и дома.',
	},
	{
		query: 'asus_rog_strix',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 28,
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUZvnYn_7TqVi5tz987AbQ_nkoO0iPd6Jr-g&s',
		star: 4.9,
		total_order: 5500,
		title: 'Ноутбук ASUS ROG Strix, 1TB SSD',
		total: 35,
		cost: '15 000 000',
		old_cost: '16 500 000',
		on_mounth: '1 800 000',
		about_tovar: [
			'Процессор: Intel i9',
			'Оперативная память: 32GB',
			'Экран: 17.3" Full HD',
		],
		description:
			'ASUS ROG Strix — это мощный игровой ноутбук с превосходной производительностью и современным дизайном.',
	},
	{
		query: 'samsung_tab_s7',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 29,
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqU7c1d95bVeEW9WitTYFa00vKifuBzIBPgQ&s',
		star: 4.8,
		total_order: 11000,
		title: 'Планшет Samsung Galaxy Tab S7, 128GB',
		total: 90,
		cost: '4 500 000',
		old_cost: '5 200 000',
		on_mounth: '550 000',
		about_tovar: ['Память: 128GB', 'Цвет: бронзовый', 'Экран: 11"'],
		description:
			'Samsung Galaxy Tab S7 — это мощный планшет с высоким разрешением и поддержкой S Pen, идеально подходящий для работы и развлечений.',
	},
	{
		query: 'jbl_charge_4',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 30,
		url: 'https://maxcom.uz/storage/product/2gKU5obXXOHPaRFOkQpvxfDx6zuUBh5OptAjNl3W.jpeg',
		star: 4.7,
		total_order: 12000,
		title: 'Портативная колонка JBL Charge 4',
		total: 60,
		cost: '1 000 000',
		old_cost: '1 300 000',
		on_mounth: '120 000',
		about_tovar: [
			'Время работы: до 20 часов',
			'Подключение: Bluetooth',
			'Влагозащита: IPX7',
		],
		description:
			'JBL Charge 4 — это портативная колонка с мощным звуком и длительным временем работы, идеально подходящая для вечеринок и активного отдыха.',
	},
	{
		query: 'canon_eos_m50',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 31,
		url: 'https://assets.asaxiy.uz/product/items/desktop/1d6585c343a6a950295242bc8bcbe3202022021121063581355LCsnxcx2XS.jpg.webp',
		star: 4.8,
		total_order: 4000,
		title: 'Фотоаппарат Canon EOS M50, 24.1MP',
		total: 30,
		cost: '6 000 000',
		old_cost: '7 200 000',
		on_mounth: '720 000',
		about_tovar: [
			'Разрешение: 24.1MP',
			'Тип матрицы: APS-C',
			'Видеосъемка: 4K',
		],
		description:
			'Canon EOS M50 — это компактная беззеркальная камера с высоким качеством изображения и 4K-видеосъемкой.',
	},
	{
		query: 'gopro_hero_9',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 32,
		url: 'https://olcha.uz/image/700x700/products/2021-11-18/kamera-gopro-hero9-black-27404-7.jpeg',
		star: 4.9,
		total_order: 6000,
		title: 'Экшн-камера GoPro Hero 9',
		total: 50,
		cost: '3 500 000',
		old_cost: '4 200 000',
		on_mounth: '420 000',
		about_tovar: [
			'Разрешение: 20MP',
			'Видео: 5K',
			'Водонепроницаемость: до 10 м',
		],
		description:
			'GoPro Hero 9 — это продвинутая экшн-камера с высоким разрешением видео и отличной стабилизацией, идеально подходящая для активного отдыха.',
	},
	{
		query: 'sony_bravia_x90j',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 33,
		url: 'https://olcha.uz/image/400x400/products/2022-02-08/televizor-sony-xr-65x90j-65-35602-0.png',
		star: 4.9,
		total_order: 3500,
		title: 'Телевизор Sony Bravia X90J 65"',
		total: 25,
		cost: '12 000 000',
		old_cost: '13 500 000',
		on_mounth: '1 500 000',
		about_tovar: [
			'Диагональ экрана: 65"',
			'Разрешение: 4K UHD',
			'Тип экрана: LED',
		],
		description:
			'Sony Bravia X90J 65" — это телевизор с высоким разрешением и реалистичной цветопередачей, поддерживающий новейшие технологии.',
	},
	{
		query: 'apple_macbook_air_m1',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 34,
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRV_NDqICUjmxokTxsMGGLYNZZPeZYLU-7csw&s',
		star: 4.9,
		total_order: 8000,
		title: 'Ноутбук Apple MacBook Air 13" M1, 256GB',
		total: 40,
		cost: '11 000 000',
		old_cost: '12 500 000',
		on_mounth: '1 350 000',
		about_tovar: [
			'Процессор: M1',
			'Оперативная память: 8GB',
			'Экран: 13.3" Retina',
		],
		description:
			'MacBook Air с процессором M1 — это сверхтонкий и легкий ноутбук с невероятной производительностью и долгим временем работы без подзарядки.',
	},
	{
		query: 'samsung_galaxy_buds_pro',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 35,
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkkBZIkyweK3vl-prjyQ4D-5qdzJdGad1huA&s',
		star: 4.7,
		total_order: 14000,
		title: 'Беспроводные наушники Samsung Galaxy Buds Pro',
		total: 150,
		cost: '1 500 000',
		old_cost: '2 000 000',
		on_mounth: '180 000',
		about_tovar: [
			'Шумоподавление',
			'Время работы: до 18 часов',
			'Подключение: Bluetooth 5.0',
		],
		description:
			'Samsung Galaxy Buds Pro — это премиальные беспроводные наушники с активным шумоподавлением и отличным качеством звука.',
	},
	{
		query: 'nikon_z6_ii',
		category: 'electronics',
		favourite: false,
		basket: false,
		id: 36,
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs1NdjmlbuGlvbu6lokHmvS0jUX6uUqjk_bQ&s',
		star: 4.9,
		total_order: 3200,
		title: 'Беззеркальная камера Nikon Z6 II, 24.5MP',
		total: 20,
		cost: '9 800 000',
		old_cost: '11 000 000',
		on_mounth: '1 200 000',
		about_tovar: [
			'Разрешение: 24.5MP',
			'Тип матрицы: BSI-CMOS',
			'Видео: 4K UHD',
		],
		description:
			'Nikon Z6 II — это мощная беззеркальная камера с превосходным качеством изображения и поддержкой 4K-видеосъемки.',
	},
];
